version: '3'
services:

  redis:
    container_name: ${SERVICE_NAME:-archetype-service}-redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - service-network

  rabbitmq:
    container_name: ${SERVICE_NAME:-archetype-service}-rabbitmq
    image: 'rabbitmq:management'
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PWD:-guest}
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - service-network

  mongodb:
    container_name: ${SERVICE_NAME:-archetype-service}-mongodb
    image: 'mongo:latest'
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD:-admin}
    ports:
      - '27017:27017'
    networks:
      - service-network

  service:
    container_name: ${SERVICE_NAME:-archetype-service}
    build: .
    ports:
      - '9000:8080'
    networks:
      - service-network

networks:
  service-network:
    name: ${SERVICE_NAME:-archetype-service}-network
    driver: bridge