version: '3'
services:

  redis:
    container_name: ${SERVICE_NAME:-archetype-service}-redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - service-network

  rabbitmq:
    container_name: ${SERVICE_NAME:-archetype-service}-rabbitmq
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PWD:-guest}
    networks:
      - service-network

  mongodb:
    container_name: ${SERVICE_NAME:-archetype-service}-mongodb
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD:-admin}
    networks:
      - service-network

  mongo-express:
    image: 'mongo-express:latest'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PWD:-admin}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER:-admin}:${MONGO_PWD:-admin}@mongodb:27017/

  service:
    container_name: ${SERVICE_NAME:-archetype-service}
    build:
      context: .
    ports:
      - '9000:8080'
    env_file:
      - .env
    networks:
      - service-network

networks:
  service-network:
    name: ${SERVICE_NAME:-archetype-service}-network
    driver: bridge