spring:
  component-scan:
    base-package: ${SCAN_BASE_PACKAGE:br.com.diegosst.archetype}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PWD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:archetype}:${MONGO_PWD:archetype}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}
      database: ${MONGO_DB:archetype}
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG